#ifndef LOGGING_H
#define LOGGING_H
#include <QLoggingCategory>
Q_DECLARE_LOGGING_CATEGORY(rxRcpIo)
Q_DECLARE_LOGGING_CATEGORY(presetIo)
Q_DECLARE_LOGGING_CATEGORY(rxWatchdogIo)
Q_DECLARE_LOGGING_CATEGORY(txWatchdogIo)
Q_DECLARE_LOGGING_CATEGORY(logicIo)
Q_DECLARE_LOGGING_CATEGORY(rxHeadIo)
Q_DECLARE_LOGGING_CATEGORY(txHeadIo)
Q_DECLARE_LOGGING_CATEGORY(xptIo)
Q_DECLARE_LOGGING_CATEGORY(requestIo)

class logging
{
public:
    logging();
};

#endif // LOGGING_H
